#!groovy
pipeline {

    agent any
    	parameters { 
	    choice(name: 'action', choices: ['create', 'destroy'], description: 'Choose create or destroy')
	    string(name: 'env', defaultValue: '', description: '')
	    booleanParam( defaultValue: true, name: 'Boolean-value' )
	}

    stages {
        stage('STAGE-1') {
            steps {
                sh 'echo "testing1......"'
	    }
    }

         stage('STAGE2') {
             steps {
               sh 'echo "testing2......"'
               echo 'Hello world!'
               echo "mesage: ${params.action}"
	       echo "message: ${params.env}"
        }
    }
  }
}
